import type { Lang } from "../types";

export const translations = {
  en: {
    nav: {
      summary: "Summary",
      corpus: "Corpus",
      nlp: "Text & NLP",
      findings: "Findings",
      map: "Case studies",
      sources: "Sources",
      methodology: "Methodology",
      repro: "Reproduce",
    },
    hero: {
      eyebrow: "NLP · Text Mining · Environmental Economics",
      headline: "Fracking in the Literature",
      subhead:
        "What the evidence says across papers, places and case studies",
      description:
        "A text-mining and evidence-synthesis reading of four academic papers on hydraulic fracturing (UOGD) — economics, water, chemistry and engineering, cross-read for what actually converges.",
      ctaGithub: "View on GitHub",
      ctaMethodology: "Read methodology",
      scrollHint: "Scroll to explore",
    },
    common: {
      viewAnalysis: "View analysis",
      readMethodology: "Read methodology",
      github: "GitHub",
      sources: "Sources",
      caseStudies: "Case studies",
      pending: "Pending verification",
      pendingCoordinates: "Coordinates pending — region-level only",
      author: "Author",
      journal: "Journal",
      year: "Year",
      type: "Type",
      link: "Source",
      close: "Close",
    },
    summary: {
      eyebrow: "01 — Executive summary",
      title: "Four papers, one binding constraint",
      intro:
        "This project reads four peer-reviewed and working-paper reviews of hydraulic fracturing side by side — not to average their conclusions, but to see where independent literatures converge. The synthesis below is drawn directly from the papers' own findings sections; nothing here is inferred beyond what each paper states.",
    },
    corpus: {
      eyebrow: "02 — Corpus overview",
      title: "What was analyzed",
      intro:
        "The corpus is deliberately small and deep: four full-length review articles, chosen for disciplinary range rather than volume — economics, hydrology, chemical engineering and petroleum engineering, each looking at the same industry from a different bench.",
      papers: "Papers",
      pages: "Pages",
      tokens: "Tokens",
      figures: "Figures extracted",
      vocab: "Unique lemmas",
      period: "Publication window",
      languages: "Source language",
      perPaper: "Corpus by paper",
    },
    nlp: {
      eyebrow: "03 — Text & NLP analysis",
      title: "How the text was processed",
      intro:
        "The extraction pipeline (PyMuPDF + spaCy) produces page-level text, lemmatized tokens and embedded figures for each paper. The subsections below show what the current pipeline outputs, and mark clearly what it does not yet compute.",
      pipeline: "Pipeline output",
      pipelineDesc:
        "Per-page text, section detection, cleaned text (citations and boilerplate stripped), full and content-bearing lemmas, and an embedded-figure index — generated by scripts/extract_lemmatize.py.",
      corpusComposition: "Corpus composition by paper",
      notYet: "Not yet computed",
      notYetItems: [
        "Sentiment analysis / polarity scoring",
        "Topic modeling or keyword clustering",
        "N-gram frequency tables",
        "Named-entity extraction (organizations, locations, chemicals)",
        "Co-occurrence network between terms",
      ],
      notYetDesc:
        "The pipeline extracts and lemmatizes text but does not yet run these downstream models. Listed here so the roadmap is explicit rather than silently missing.",
      recoveryRateLabel: "FPW recovery rate — % of injected fluid",
      recoveryRateCaption: "Flowback / produced-water recovery, as documented independently by P02 and P03.",
    },
    findings: {
      eyebrow: "04 — Findings",
      title: "Findings by theme",
      intro:
        "Every claim below is attributed to the paper that makes it. Themes group findings that recur across papers; they do not imply the papers agree on magnitude or mechanism.",
      themes: {
        environment: "Environmental concerns",
        health: "Health & public health",
        water: "Water & contamination",
        economy: "Economic benefits & costs",
        justice: "Regulation, governance & environmental justice",
        seismicity: "Induced seismicity",
      },
      sourceLabel: "Source",
    },
    map: {
      eyebrow: "05 — Interactive case study map",
      title: "Where the evidence is grounded",
      intro:
        "Markers show places named as case studies or empirical settings inside the four papers — not a systematic geocoding of every location mentioned. Precision varies: some are county-level (Denton, TX), some are state/region-level. Coordinates use the town, county or region's known public location, not study-specific site data, which the papers do not disclose.",
      legendTitle: "Theme",
      precisionLabel: "Precision",
      precisionCounty: "County / site level",
      precisionState: "State / region level",
      paperLabel: "Paper",
      topicLabel: "Topic",
    },
    sources: {
      eyebrow: "06 — Sources & evidence",
      title: "The four papers",
      intro:
        "Full bibliographic detail for every paper in the corpus, with links to the original source where publicly available.",
      table: {
        id: "ID",
        title: "Title",
        authors: "Authors",
        journal: "Journal / venue",
        year: "Year",
        type: "Type",
        link: "Link",
      },
    },
    methodology: {
      eyebrow: "07 — Methodology",
      title: "How this was built",
      collection: {
        title: "Collection",
        body: "Four papers were selected manually for disciplinary breadth on hydraulic fracturing / UOGD: an economics literature review (P01), a water-and-seismicity systematic review (P02), a chemical-engineering review of HF fluid risk (P03), and a petroleum-engineering materials review on produced-water reuse (P04). This is a small, purposively sampled corpus, not a systematic literature search.",
      },
      cleaning: {
        title: "Text cleaning",
        body: "PyMuPDF extracts text in reading order per page. A regex layer strips URLs, inline citations, running headers/footers and page numbers, and detects section headers against a fixed list of common academic section names.",
      },
      nlpMethod: {
        title: "NLP pipeline",
        body: "spaCy (en_core_web_sm/lg) lemmatizes every page, keeping nouns, verbs, adjectives, adverbs and proper nouns, and dropping stopwords and short tokens. Output is stored per paper as a page-level CSV (page, section, raw text, cleaned text, full lemmas, content lemmas, token count).",
      },
      sentiment: {
        title: "Sentiment model",
        body: "Not yet implemented. No lexicon or model has been applied to this corpus — any sentiment claim would be invented. This is listed as a next step, not a shipped feature.",
      },
      mapping: {
        title: "How case studies were mapped",
        body: "Locations were read manually from each paper's text (e.g. Denton TX, Garfield County CO, Oklahoma). Coordinates are the public, known coordinates of the named place — not precise well or study-site coordinates, which the source papers do not publish. Precision is marked per marker.",
      },
      limitations: {
        title: "Limitations",
        items: [
          "Section detection is heuristic and tuned to standard academic structure; it can miss atypical headers.",
          "Citation-removal regex is pattern-based and may leave some inline references intact.",
          "No OCR is run on figures — only page text is captured, not text embedded inside images.",
          "en_core_web_sm has materially lower named-entity accuracy than en_core_web_lg.",
          "The corpus is four papers, purposively selected — it is a close reading, not a systematic review or a statistically representative sample.",
        ],
      },
      future: {
        title: "What should improve next",
        items: [
          "Run a domain-tuned sentiment/stance model over the cleaned corpus.",
          "Add topic modeling (e.g. BERTopic or LDA) across the four papers to surface latent themes beyond manual coding.",
          "Build a term co-occurrence network from lemmas_useful.",
          "Expand the corpus beyond four papers with a documented, reproducible search strategy.",
          "Add precise site-level coordinates where a paper explicitly discloses them.",
        ],
      },
    },
    repro: {
      eyebrow: "08 — Repository & reproducibility",
      title: "Run it yourself",
      intro:
        "The extraction pipeline and this website are both in the same repository. The pipeline requires the original PDFs locally (not committed, for copyright reasons); the website only needs the committed data files.",
      runPipeline: "Run the extraction pipeline",
      runSite: "Run the website locally",
      dataLimitations: "Data limitations",
      dataLimitationsBody:
        "Raw and processed text (data/raw, data/processed) and the figure/metadata CSVs (outputs/) are generated locally and are gitignored — they are not in this repository. The committed figures/ folder and the findings written into this site are the durable, versioned outputs of that pipeline.",
    },
    footer: {
      name: "Juan David Muñoz",
      role: "Economics · Data Science · Public Policy · NLP",
      rights: "Research and analysis published for educational and portfolio purposes.",
    },
  },
  es: {
    nav: {
      summary: "Resumen",
      corpus: "Corpus",
      nlp: "Texto y NLP",
      findings: "Hallazgos",
      map: "Casos de estudio",
      sources: "Fuentes",
      methodology: "Metodología",
      repro: "Reproducir",
    },
    hero: {
      eyebrow: "NLP · Minería de texto · Economía ambiental",
      headline: "Fracking en la literatura",
      subhead: "Qué dice la evidencia entre papers, lugares y casos de estudio",
      description:
        "Una lectura de minería de texto y síntesis de evidencia de cuatro artículos académicos sobre fracturamiento hidráulico (UOGD) — economía, agua, química e ingeniería, leídos en conjunto para ver qué converge realmente.",
      ctaGithub: "Ver en GitHub",
      ctaMethodology: "Leer metodología",
      scrollHint: "Desplázate para explorar",
    },
    common: {
      viewAnalysis: "Ver análisis",
      readMethodology: "Leer metodología",
      github: "GitHub",
      sources: "Fuentes",
      caseStudies: "Casos de estudio",
      pending: "Pendiente de verificación",
      pendingCoordinates: "Coordenadas pendientes — solo a nivel de región",
      author: "Autor",
      journal: "Revista",
      year: "Año",
      type: "Tipo",
      link: "Fuente",
      close: "Cerrar",
    },
    summary: {
      eyebrow: "01 — Resumen ejecutivo",
      title: "Cuatro artículos, una restricción vinculante",
      intro:
        "Este proyecto lee en conjunto cuatro revisiones académicas (arbitradas y de working paper) sobre fracturamiento hidráulico — no para promediar sus conclusiones, sino para ver dónde convergen literaturas independientes. La síntesis a continuación proviene directamente de las secciones de hallazgos de cada artículo; nada aquí se infiere más allá de lo que cada artículo afirma.",
    },
    corpus: {
      eyebrow: "02 — Panorama del corpus",
      title: "Qué se analizó",
      intro:
        "El corpus es deliberadamente pequeño y profundo: cuatro artículos de revisión completos, elegidos por amplitud disciplinar más que por volumen — economía, hidrología, ingeniería química e ingeniería de petróleos, cada uno mirando la misma industria desde un banco distinto.",
      papers: "Artículos",
      pages: "Páginas",
      tokens: "Tokens",
      figures: "Figuras extraídas",
      vocab: "Lemas únicos",
      period: "Ventana de publicación",
      languages: "Idioma de las fuentes",
      perPaper: "Corpus por artículo",
    },
    nlp: {
      eyebrow: "03 — Texto y análisis NLP",
      title: "Cómo se procesó el texto",
      intro:
        "El pipeline de extracción (PyMuPDF + spaCy) produce texto por página, tokens lematizados y figuras embebidas para cada artículo. Las subsecciones muestran lo que el pipeline actual produce, y marcan claramente lo que aún no calcula.",
      pipeline: "Salida del pipeline",
      pipelineDesc:
        "Texto por página, detección de secciones, texto limpio (citas y ruido eliminados), lemas completos y lemas con carga semántica, e índice de figuras embebidas — generado por scripts/extract_lemmatize.py.",
      corpusComposition: "Composición del corpus por artículo",
      notYet: "Aún no calculado",
      notYetItems: [
        "Análisis de sentimiento / puntaje de polaridad",
        "Modelado de tópicos o agrupación de palabras clave",
        "Tablas de frecuencia de n-gramas",
        "Extracción de entidades nombradas (organizaciones, lugares, químicos)",
        "Red de co-ocurrencia entre términos",
      ],
      notYetDesc:
        "El pipeline extrae y lematiza el texto, pero aún no ejecuta estos modelos posteriores. Se listan aquí para que la hoja de ruta sea explícita y no una ausencia silenciosa.",
      recoveryRateLabel: "Tasa de recuperación de FPW — % del fluido inyectado",
      recoveryRateCaption: "Recuperación de agua de retorno/producida, documentada independientemente por P02 y P03.",
    },
    findings: {
      eyebrow: "04 — Hallazgos",
      title: "Hallazgos por tema",
      intro:
        "Cada afirmación a continuación está atribuida al artículo que la hace. Los temas agrupan hallazgos que se repiten entre artículos; no implican que los artículos coincidan en magnitud o mecanismo.",
      themes: {
        environment: "Preocupaciones ambientales",
        health: "Salud y salud pública",
        water: "Agua y contaminación",
        economy: "Beneficios y costos económicos",
        justice: "Regulación, gobernanza y justicia ambiental",
        seismicity: "Sismicidad inducida",
      },
      sourceLabel: "Fuente",
    },
    map: {
      eyebrow: "05 — Mapa interactivo de casos de estudio",
      title: "Dónde se ancla la evidencia",
      intro:
        "Los marcadores muestran lugares mencionados como casos de estudio o entornos empíricos dentro de los cuatro artículos — no una geocodificación sistemática de cada lugar mencionado. La precisión varía: algunos son a nivel de condado (Denton, TX), otros a nivel estatal o regional. Las coordenadas usan la ubicación pública conocida del pueblo, condado o región, no datos de sitio específicos del estudio, que los artículos no revelan.",
      legendTitle: "Tema",
      precisionLabel: "Precisión",
      precisionCounty: "Nivel de condado / sitio",
      precisionState: "Nivel de estado / región",
      paperLabel: "Artículo",
      topicLabel: "Tema",
    },
    sources: {
      eyebrow: "06 — Fuentes y evidencia",
      title: "Los cuatro artículos",
      intro:
        "Detalle bibliográfico completo de cada artículo del corpus, con enlaces a la fuente original cuando está disponible públicamente.",
      table: {
        id: "ID",
        title: "Título",
        authors: "Autores",
        journal: "Revista / medio",
        year: "Año",
        type: "Tipo",
        link: "Enlace",
      },
    },
    methodology: {
      eyebrow: "07 — Metodología",
      title: "Cómo se construyó",
      collection: {
        title: "Recolección",
        body: "Se seleccionaron manualmente cuatro artículos por su amplitud disciplinar sobre fracturamiento hidráulico / UOGD: una revisión económica (P01), una revisión sistemática de agua y sismicidad (P02), una revisión de ingeniería química sobre riesgo del fluido HF (P03), y una revisión de ciencia de materiales de ingeniería de petróleos sobre reutilización de agua producida (P04). Es un corpus pequeño y de muestreo intencional, no una búsqueda sistemática de literatura.",
      },
      cleaning: {
        title: "Limpieza de texto",
        body: "PyMuPDF extrae el texto en orden de lectura por página. Una capa de expresiones regulares elimina URLs, citas en línea, encabezados/pies de página repetidos y números de página, y detecta encabezados de sección contra una lista fija de nombres de sección académicos comunes.",
      },
      nlpMethod: {
        title: "Pipeline de NLP",
        body: "spaCy (en_core_web_sm/lg) lematiza cada página, conservando sustantivos, verbos, adjetivos, adverbios y nombres propios, y descartando stopwords y tokens cortos. La salida se guarda por artículo como un CSV a nivel de página (página, sección, texto crudo, texto limpio, lemas completos, lemas útiles, conteo de tokens).",
      },
      sentiment: {
        title: "Modelo de sentimiento",
        body: "Aún no implementado. No se ha aplicado ningún léxico ni modelo a este corpus — cualquier afirmación de sentimiento sería inventada. Se lista como próximo paso, no como funcionalidad ya entregada.",
      },
      mapping: {
        title: "Cómo se mapearon los casos de estudio",
        body: "Las ubicaciones se leyeron manualmente del texto de cada artículo (p. ej. Denton TX, Condado de Garfield CO, Oklahoma). Las coordenadas son las públicas y conocidas del lugar nombrado — no coordenadas precisas de pozo o sitio de estudio, que los artículos fuente no publican. La precisión se marca por cada marcador.",
      },
      limitations: {
        title: "Limitaciones",
        items: [
          "La detección de secciones es heurística y está ajustada a la estructura académica estándar; puede omitir encabezados atípicos.",
          "La expresión regular para eliminar citas es basada en patrones y puede dejar algunas referencias en línea intactas.",
          "No se ejecuta OCR sobre las figuras — solo se captura el texto de la página, no el texto embebido dentro de las imágenes.",
          "en_core_web_sm tiene una precisión de entidades nombradas notablemente menor que en_core_web_lg.",
          "El corpus son cuatro artículos, seleccionados intencionalmente — es una lectura cercana, no una revisión sistemática ni una muestra estadísticamente representativa.",
        ],
      },
      future: {
        title: "Qué mejorar a continuación",
        items: [
          "Ejecutar un modelo de sentimiento/postura ajustado al dominio sobre el corpus limpio.",
          "Agregar modelado de tópicos (p. ej. BERTopic o LDA) entre los cuatro artículos para revelar temas latentes más allá de la codificación manual.",
          "Construir una red de co-ocurrencia de términos a partir de lemmas_useful.",
          "Ampliar el corpus más allá de cuatro artículos con una estrategia de búsqueda documentada y reproducible.",
          "Agregar coordenadas precisas a nivel de sitio donde un artículo las revele explícitamente.",
        ],
      },
    },
    repro: {
      eyebrow: "08 — Repositorio y reproducibilidad",
      title: "Ejecútalo tú mismo",
      intro:
        "El pipeline de extracción y este sitio web están en el mismo repositorio. El pipeline requiere los PDFs originales de forma local (no versionados, por derechos de autor); el sitio web solo necesita los archivos de datos versionados.",
      runPipeline: "Ejecutar el pipeline de extracción",
      runSite: "Ejecutar el sitio web localmente",
      dataLimitations: "Limitaciones de los datos",
      dataLimitationsBody:
        "El texto crudo y procesado (data/raw, data/processed) y los CSV de figuras/metadatos (outputs/) se generan localmente y están en .gitignore — no están en este repositorio. La carpeta figures/ versionada y los hallazgos escritos en este sitio son las salidas durables y versionadas de ese pipeline.",
    },
    footer: {
      name: "Juan David Muñoz",
      role: "Economía · Ciencia de Datos · Política Pública · NLP",
      rights: "Investigación y análisis publicados con fines educativos y de portafolio.",
    },
  },
} satisfies Record<Lang, unknown>;

export type Translations = typeof translations.en;
